import Foundation

// v1.5.1 — feature catalogs split out of MockData.
// These are static FEATURE DEFINITIONS (activity types, date cards, quiz
// questions). They are NOT user data and ship with the app like strings or
// images do. Renamed out of `MockData` so the audit rule "no MockData
// outside #Preview" is mechanical.
//
// v1.6.0 — date card pool expanded to 120 HK-rooted ideas across vibes:
// 浪漫 / 屋企 / 玩樂 / 探險 / 食 / 文化 / 影相 / 慢活 / 學嘢 / 懷舊 / 靜 / 夢想.
// Mirrors android/.../data/ActivityCatalog.kt — keep both in sync.

enum ActivityCatalog {
    static let all: [Activity] = [
        Activity(id: "a1", title: "盲盒約會", subtitle: "抽一張卡，跟住做", kind: .cards, count: 120),
        Activity(id: "a2", title: "21 條問題", subtitle: "了解多啲對方", kind: .quiz, count: 21),
        // v1.1.0 — 18 districts, journal each one as you visit.
        Activity(id: "a3", title: "18 區日記", subtitle: "一齊行勻香港，一區一篇", kind: .districts, count: 18),
        // v1.3.0 — MTR 站日記. 90 stations across 9 lines.
        Activity(id: "a4", title: "MTR 站日記", subtitle: "一齊搭遍 MTR，一站一篇", kind: .mtr, count: 90),
    ]
}

enum DateCardCatalog {
    static let all: [DateCard] = [
        // ── 浪漫 (romantic) ──
        DateCard(id: 1, title: "夜遊維港",
                 detail: "搭天星小輪，喺甲板上面影返張合照",
                 mood: "浪漫", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$"),
        DateCard(id: 2, title: "太平山頂睇夜景",
                 detail: "唔搭纜車，搭巴士上山，行盧吉道一個圈",
                 mood: "浪漫", kaomoji: "(♡´︶`♡)", tint: .rose, cost: "$"),
        DateCard(id: 3, title: "中環摩天輪",
                 detail: "黃昏嗰場，一卡兩個人，影 360 度",
                 mood: "浪漫", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$"),
        DateCard(id: 4, title: "西環泳棚日落",
                 detail: "黃昏前到，等天色變紫，影一張剪影",
                 mood: "浪漫", kaomoji: "(´｡• ᵕ •｡`) ♡", tint: .rose, cost: "$"),
        DateCard(id: 5, title: "石澳睇日落",
                 detail: "海邊石灘，帶杯熱嘢飲坐到天黑",
                 mood: "浪漫", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$"),
        DateCard(id: 6, title: "維港遊船 dinner cruise",
                 detail: "揀個有 buffet 嘅，食住睇煙花碼頭",
                 mood: "浪漫", kaomoji: "(♡´︶`♡)", tint: .rose, cost: "$$$"),
        DateCard(id: 7, title: "山頂纜車黃昏一程",
                 detail: "唔上頂，淨係坐個來回，影沿途光線",
                 mood: "浪漫", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$"),
        DateCard(id: 8, title: "尖沙咀海濱散步",
                 detail: "由文化中心行去星光大道，8 點睇幻彩詠香江",
                 mood: "浪漫", kaomoji: "(´｡• ᵕ •｡`)", tint: .rose, cost: "$"),
        DateCard(id: 9, title: "香港仔避風塘食艇仔",
                 detail: "搭舢舨入避風塘，叫一隻艇仔粉一齊食",
                 mood: "浪漫", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$"),
        DateCard(id: 10, title: "整一餐情人節食物",
                 detail: "今晚煮個 valentine special，唔理乜日子",
                 mood: "浪漫", kaomoji: "(♡´︶`♡)", tint: .rose, cost: "$"),
        DateCard(id: 11, title: "寫一封情書畀對方",
                 detail: "10 分鐘 timer，唔可以 google，交換睇",
                 mood: "浪漫", kaomoji: "(´｡• ᵕ •｡`) ♡", tint: .rose, cost: "$"),
        DateCard(id: 12, title: "Skybar 雞尾酒",
                 detail: "中環或尖沙咀 rooftop，揀杯顏色靚嘅",
                 mood: "浪漫", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$$"),

        // ── 屋企 (at home) ──
        DateCard(id: 13, title: "一齊整 pancake",
                 detail: "揀一個未試過嘅口味，最差嗰個負責洗碗",
                 mood: "屋企", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 14, title: "一齊煲劇 marathon",
                 detail: "揀一套兩個都未睇過嘅，一晚煲完",
                 mood: "屋企", kaomoji: "(─‿─)", tint: .amber, cost: "$"),
        DateCard(id: 15, title: "係屋企整 cocktail",
                 detail: "YouTube 學一隻新嘅，互相試味",
                 mood: "屋企", kaomoji: "(¬‿¬)", tint: .rose, cost: "$"),
        DateCard(id: 16, title: "一齊砌 LEGO",
                 detail: "買一套兩個一齊砌，邊砌邊吹水",
                 mood: "屋企", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$$"),
        DateCard(id: 17, title: "共做窩夫早餐",
                 detail: "周日早上慢慢整，配 cold brew 或熱茶",
                 mood: "屋企", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 18, title: "屋企 movie night",
                 detail: "搭帳篷喺廳，買爆谷，揀套經典戲",
                 mood: "屋企", kaomoji: "(◕‿◕)", tint: .amber, cost: "$"),
        DateCard(id: 19, title: "一齊砌 puzzle",
                 detail: "買 500 塊嘅，邊砌邊聽 playlist",
                 mood: "屋企", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$"),
        DateCard(id: 20, title: "煮韓式部隊鍋",
                 detail: "去 City'super 買齊料，火鍋慢慢食",
                 mood: "屋企", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$$"),
        DateCard(id: 21, title: "屋企 spa night",
                 detail: "敷面膜、開精油、聽 lo-fi，互相按頭",
                 mood: "屋企", kaomoji: "(˘ω˘)", tint: .rose, cost: "$"),
        DateCard(id: 22, title: "一齊整壽司卷",
                 detail: "買米同紫菜，自己搵料，邊整邊食",
                 mood: "屋企", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 23, title: "煲老火湯",
                 detail: "落街市買藥材，慢火煲 3 個鐘",
                 mood: "屋企", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$"),
        DateCard(id: 24, title: "一齊煲 K-drama",
                 detail: "揀一套兩個都聽到推薦嘅，唔好劇透",
                 mood: "屋企", kaomoji: "(─‿─)", tint: .amber, cost: "$"),
        DateCard(id: 25, title: "整 ramen 比賽",
                 detail: "各人整一碗，對方評分，輸嗰個洗碗",
                 mood: "屋企", kaomoji: "(¬‿¬)", tint: .amber, cost: "$"),

        // ── 玩樂 (fun) ──
        DateCard(id: 26, title: "影貼紙相",
                 detail: "銅鑼灣或旺角，搞笑款 4 連張",
                 mood: "玩樂", kaomoji: "(≧▽≦)", tint: .rose, cost: "$"),
        DateCard(id: 27, title: "盲交換禮物",
                 detail: "$50 budget，30 分鐘內入便利店揀",
                 mood: "玩樂", kaomoji: "(¬‿¬)", tint: .sage, cost: "$"),
        DateCard(id: 28, title: "去茶餐廳食 brunch",
                 detail: "揀間冇去過嘅，每人叫一個 set，分嚟食",
                 mood: "玩樂", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 29, title: "一齊去做運動",
                 detail: "踩單車／瑜珈／游水，揀一樣兩個都未試過",
                 mood: "玩樂", kaomoji: "(•̀ᴗ•́)و", tint: .sage, cost: "$"),
        DateCard(id: 30, title: "玩 board game café",
                 detail: "佐敦或太子，揀一隻冇玩過嘅",
                 mood: "玩樂", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 31, title: "做心理測驗",
                 detail: "搵一個 personality test，互相估對方答",
                 mood: "玩樂", kaomoji: "(≧▽≦)", tint: .amber, cost: "$"),
        DateCard(id: 32, title: "KTV 包房",
                 detail: "中午 happy hour 時段，唱足 3 個鐘",
                 mood: "玩樂", kaomoji: "(≧▽≦)", tint: .rose, cost: "$$"),
        DateCard(id: 33, title: "Escape Room 走出旺角",
                 detail: "揀一個中等難度，60 分鐘出唔到再諗計",
                 mood: "玩樂", kaomoji: "(¬‿¬)", tint: .sage, cost: "$$"),
        DateCard(id: 34, title: "Bowling 二人賽",
                 detail: "輸嗰個請食晚飯，三局決勝",
                 mood: "玩樂", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 35, title: "室內攀岩 JCC",
                 detail: "新手 wall 都好玩，輪流 belay",
                 mood: "玩樂", kaomoji: "(•̀ᴗ•́)و", tint: .sage, cost: "$$"),
        DateCard(id: 36, title: "ICE skating Mega Box",
                 detail: "揀平日下晝，人少又凍",
                 mood: "玩樂", kaomoji: "(≧▽≦)", tint: .sage, cost: "$$"),
        DateCard(id: 37, title: "Mini golf 沙田",
                 detail: "18 個洞，當散步又當比賽",
                 mood: "玩樂", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 38, title: "Trampoline park",
                 detail: "BounceInc 觀塘，跳到出汗",
                 mood: "玩樂", kaomoji: "(≧▽≦)", tint: .sage, cost: "$$"),
        DateCard(id: 39, title: "夾公仔大挑戰",
                 detail: "旺角信和或荷里活，$100 limit",
                 mood: "玩樂", kaomoji: "(¬‿¬)", tint: .rose, cost: "$"),
        DateCard(id: 40, title: "桌球室一場",
                 detail: "新手亦可，輸嗰個唱一首歌",
                 mood: "玩樂", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),

        // ── 探險 (adventure) ──
        DateCard(id: 41, title: "行一條未行過嘅街",
                 detail: "Google Maps 隨機 drop pin，去最近嗰條",
                 mood: "探險", kaomoji: "(´｡• ω •｡`)", tint: .sage, cost: "$"),
        DateCard(id: 42, title: "夜晚行山睇夜景",
                 detail: "獅子山或大潭，記得帶電筒",
                 mood: "探險", kaomoji: "(•̀ᴗ•́)و", tint: .sage, cost: "$"),
        DateCard(id: 43, title: "龍脊日落",
                 detail: "由土地灣行入，3 個鐘搞掂",
                 mood: "探險", kaomoji: "(•̀ᴗ•́)و", tint: .sage, cost: "$"),
        DateCard(id: 44, title: "西貢獨木舟",
                 detail: "白沙灣或半月灣，租兩個鐘",
                 mood: "探險", kaomoji: "(≧▽≦)", tint: .sage, cost: "$$"),
        DateCard(id: 45, title: "鹽田仔尋墟",
                 detail: "西貢搭船入，行客家村落",
                 mood: "探險", kaomoji: "(´｡• ω •｡`)", tint: .sage, cost: "$"),
        DateCard(id: 46, title: "香港地質公園",
                 detail: "東平洲一日遊，睇千層糕岩石",
                 mood: "探險", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 47, title: "大澳食艇仔粉",
                 detail: "搭巴士入，行棚屋，順便睇白海豚",
                 mood: "探險", kaomoji: "(っ˘ڡ˘ς)", tint: .sage, cost: "$"),
        DateCard(id: 48, title: "嘉道理農場睇動物",
                 detail: "大埔出發，行勻成個園 5 個鐘",
                 mood: "探險", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 49, title: "麥理浩徑第二段",
                 detail: "西灣到鹹田，影千古浪潮",
                 mood: "探險", kaomoji: "(•̀ᴗ•́)و", tint: .sage, cost: "$"),
        DateCard(id: 50, title: "塔門紮營",
                 detail: "黃石碼頭搭船入，星空無敵",
                 mood: "探險", kaomoji: "(✧ω✧)", tint: .sage, cost: "$$"),
        DateCard(id: 51, title: "夜遊鯉魚門",
                 detail: "賞夜景＋食海鮮，揀條街市旁邊嘅",
                 mood: "探險", kaomoji: "(´｡• ω •｡`)", tint: .sage, cost: "$$"),

        // ── 食 (food) ──
        DateCard(id: 52, title: "深水埗街頭小食巡禮",
                 detail: "由福榮街行到鴨寮街，每檔試一樣",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 53, title: "天后廟街宵夜大排檔",
                 detail: "凌晨先去，叫煲仔飯同椒鹽鮮魷",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$$"),
        DateCard(id: 54, title: "米芝蓮車仔麵盲試",
                 detail: "揀 3 間有得獎嘅，逐間試打分",
                 mood: "食", kaomoji: "(¬‿¬)", tint: .amber, cost: "$$"),
        DateCard(id: 55, title: "去街市買餸",
                 detail: "唔講食乜，望住有咩買咩，返屋企 freestyle",
                 mood: "食", kaomoji: "(￣ω￣)", tint: .amber, cost: "$"),
        DateCard(id: 56, title: "灣仔早茶",
                 detail: "龍門大酒樓嗰類，叫蝦餃燒賣鳳爪",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$$"),
        DateCard(id: 57, title: "九龍城泰國菜街",
                 detail: "城南道隨便揀一間，叫冬蔭功＋椰青",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$$"),
        DateCard(id: 58, title: "西貢海鮮街",
                 detail: "揀條魚請廚房代煮，加碟蒜蓉炒菜",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$$$"),
        DateCard(id: 59, title: "上環日式居酒屋",
                 detail: "Hidden 嗰啲，叫熱清酒＋串燒拼盤",
                 mood: "食", kaomoji: "(´◔౪◔)", tint: .amber, cost: "$$"),
        DateCard(id: 60, title: "甜品大會",
                 detail: "一晚跑 3 間糖水鋪，每人揀一樣",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .rose, cost: "$$"),
        DateCard(id: 61, title: "牛雜車仔",
                 detail: "搵間排隊嗰啲，企住食",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 62, title: "本土微醺酒吧",
                 detail: "卑利街或太子，揀杯試新調酒",
                 mood: "食", kaomoji: "(¬‿¬)", tint: .rose, cost: "$$"),
        DateCard(id: 63, title: "蛋撻馬拉松",
                 detail: "由泰昌行到檀島，比較邊間最香",
                 mood: "食", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$"),
        DateCard(id: 64, title: "Omakase 一次",
                 detail: "$1k 以下都有，揀 lunch set 較抵",
                 mood: "食", kaomoji: "(´｡• ᵕ •｡`)", tint: .amber, cost: "$$$"),

        // ── 文化 (culture) ──
        DateCard(id: 65, title: "M+ 睇展",
                 detail: "揀個 special exhibition，行 3 個鐘",
                 mood: "文化", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 66, title: "PMQ 文青週末",
                 detail: "上去睇手作 pop-up，順便食 cafe",
                 mood: "文化", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 67, title: "灣仔藍屋導覽",
                 detail: "預約唐樓 tour，了解戰前歷史",
                 mood: "文化", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 68, title: "大館睇 art",
                 detail: "中環 Tai Kwun，加埋 cafe 食 scone",
                 mood: "文化", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 69, title: "Tai Kwun book fair",
                 detail: "週末市集，揀本中古書送對方",
                 mood: "文化", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 70, title: "香港藝術館",
                 detail: "尖沙咀，揀個香港藝術家展覽",
                 mood: "文化", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 71, title: "歷史博物館",
                 detail: "尖沙咀，行香港故事常設展",
                 mood: "文化", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 72, title: "獨立電影 Broadway",
                 detail: "油麻地電影中心，揀套冷門法國片",
                 mood: "文化", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$$"),
        DateCard(id: 73, title: "西九戲曲中心",
                 detail: "茶館劇場，新手粵劇入門",
                 mood: "文化", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 74, title: "灣仔藝術中心",
                 detail: "睇場 indie 音樂表演",
                 mood: "文化", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$$"),

        // ── 影相 (photography) ──
        DateCard(id: 75, title: "影黑白菲林",
                 detail: "買一筒可棄菲林，行半日，影晒佢",
                 mood: "影相", kaomoji: "(◍•ᴗ•◍)", tint: .rose, cost: "$$"),
        DateCard(id: 76, title: "中環半山扶手電梯街拍",
                 detail: "由德輔道行到士丹頓街，捕捉街景",
                 mood: "影相", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 77, title: "油麻地果欄夜景",
                 detail: "凌晨 2 點開檔，霓虹同紙皮箱好出片",
                 mood: "影相", kaomoji: "(´｡• ω •｡`)", tint: .sage, cost: "$"),
        DateCard(id: 78, title: "彩虹邨幾何打卡",
                 detail: "唐樓對稱構圖，配波鞋色",
                 mood: "影相", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 79, title: "中環怪獸大廈",
                 detail: "鰂魚涌益昌大廈，仰拍密集恐懼",
                 mood: "影相", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 80, title: "西營盤龍虎山日出",
                 detail: "5 點起身，行松林廢堡睇晨曦",
                 mood: "影相", kaomoji: "(✧ω✧)", tint: .sage, cost: "$"),
        DateCard(id: 81, title: "上環海味街掃街",
                 detail: "德輔道西，影乾貨同老店招牌",
                 mood: "影相", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 82, title: "石硤尾賽馬會創意藝術中心",
                 detail: "Jockey Club 工作室開放日打卡",
                 mood: "影相", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 83, title: "深水埗大南街 cafe hop",
                 detail: "3 間 cafe 各影 1 角，砌成 IG 9 宮格",
                 mood: "影相", kaomoji: "(◍•ᴗ•◍)", tint: .rose, cost: "$$"),

        // ── 慢活 (slow living) ──
        DateCard(id: 84, title: "海濱長廊踩單車",
                 detail: "沙田到大埔，租一日，中途食魚蛋",
                 mood: "慢活", kaomoji: "(´｡• ω •｡`)", tint: .sage, cost: "$"),
        DateCard(id: 85, title: "太空館圓頂戲院",
                 detail: "睇場 dome show，躺住睇星空",
                 mood: "慢活", kaomoji: "(˘ω˘)", tint: .sage, cost: "$"),
        DateCard(id: 86, title: "北角電車一程",
                 detail: "頭排上層，由屈地街坐到筲箕灣",
                 mood: "慢活", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 87, title: "搭叮叮一程",
                 detail: "上層頭排，由筲箕灣坐去堅尼地城",
                 mood: "慢活", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 88, title: "去離島放空",
                 detail: "南丫、長洲、坪洲，揀一個冇去過",
                 mood: "慢活", kaomoji: "(´｡• ω •｡`)", tint: .sage, cost: "$"),
        DateCard(id: 89, title: "九龍公園野餐",
                 detail: "Pacific Coffee 買三文治，鋪布坐草地",
                 mood: "慢活", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 90, title: "獨立書店 reading time",
                 detail: "見山或蒲窩，揀本書讀一個鐘",
                 mood: "慢活", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 91, title: "南區海洋公園纜車",
                 detail: "唔玩機動，淨係坐纜車睇南區海岸",
                 mood: "慢活", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 92, title: "Cafe 慢工夫沖咖啡",
                 detail: "灣仔 NOC 嗰類，叫 hand drip + 朱古力多士",
                 mood: "慢活", kaomoji: "(˘ω˘)", tint: .amber, cost: "$$"),
        DateCard(id: 93, title: "公園做瑜珈",
                 detail: "維園或迪欣湖，YouTube 跟 20 分鐘 flow",
                 mood: "慢活", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),

        // ── 學嘢 (learn together) ──
        DateCard(id: 94, title: "學做廣式月餅",
                 detail: "中秋前班，整完帶返屋企送家人",
                 mood: "學嘢", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$$"),
        DateCard(id: 95, title: "Cocktail 調酒班",
                 detail: "2 個鐘整 3 杯，加埋食物 pairing",
                 mood: "學嘢", kaomoji: "(¬‿¬)", tint: .rose, cost: "$$"),
        DateCard(id: 96, title: "一齊學跳 Salsa",
                 detail: "中環有試堂班，1 小時學基本步",
                 mood: "學嘢", kaomoji: "(✧ω✧)", tint: .rose, cost: "$$"),
        DateCard(id: 97, title: "Pottery 工作坊",
                 detail: "上水或柴灣，整對 mug 互送",
                 mood: "學嘢", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$$"),
        DateCard(id: 98, title: "整對銀戒指",
                 detail: "尖沙咀 metalsmith 班，2 個鐘整一對",
                 mood: "學嘢", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$$"),
        DateCard(id: 99, title: "Latte art 班",
                 detail: "Cupping Room 嗰類，學拉心同葉",
                 mood: "學嘢", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$$"),
        DateCard(id: 100, title: "捏陶笛工作坊",
                 detail: "完場一人一個，玩到識吹首歌",
                 mood: "學嘢", kaomoji: "(◕‿◕)", tint: .sage, cost: "$$"),
        DateCard(id: 101, title: "韓國菜班",
                 detail: "學整辣炒年糕＋韓式煎餅，現場食",
                 mood: "學嘢", kaomoji: "(っ˘ڡ˘ς)", tint: .amber, cost: "$$"),
        DateCard(id: 102, title: "侍酒師入門課",
                 detail: "中環 wine school，試 6 款紅白酒",
                 mood: "學嘢", kaomoji: "(¬‿¬)", tint: .rose, cost: "$$$"),
        DateCard(id: 103, title: "Calligraphy 班",
                 detail: "中環書法室，學行書，寫一句送對方",
                 mood: "學嘢", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$$"),

        // ── 懷舊 (nostalgia) ──
        DateCard(id: 104, title: "重做第一次 date",
                 detail: "去返第一次 date 嘅地方，影同樣 pose",
                 mood: "懷舊", kaomoji: "(´｡• ᵕ •｡`)", tint: .rose, cost: "$$"),
        DateCard(id: 105, title: "去鴨寮街掃懷舊嘢",
                 detail: "搵錄音帶、菲林機，買到當回禮",
                 mood: "懷舊", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),
        DateCard(id: 106, title: "睇舊戲院",
                 detail: "油麻地 Broadway，揀部 80 年代港產片",
                 mood: "懷舊", kaomoji: "(´｡• ω •｡`)", tint: .amber, cost: "$$"),
        DateCard(id: 107, title: "西九 graffiti wall",
                 detail: "影返廿年前舊香港 vibe",
                 mood: "懷舊", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 108, title: "茶記點對唱嘅歌",
                 detail: "搵間有點唱嘅，點 90s 廣東歌",
                 mood: "懷舊", kaomoji: "(◕‿◕)", tint: .amber, cost: "$"),
        DateCard(id: 109, title: "再食一次第一餐 date 嘅嘢",
                 detail: "重現 menu，連飲品都要一樣",
                 mood: "懷舊", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$$"),

        // ── 靜 (quiet) ──
        DateCard(id: 110, title: "寫信俾未來自己",
                 detail: "一年後拆，封住放入記憶簿",
                 mood: "靜", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$"),
        DateCard(id: 111, title: "睇夜場戲",
                 detail: "11pm 後嗰場，散場行返屋企",
                 mood: "靜", kaomoji: "(─‿─)", tint: .amber, cost: "$$"),
        DateCard(id: 112, title: "聽 vinyl 一晚",
                 detail: "去 White Noise 揀張舊唱片，返屋企播",
                 mood: "靜", kaomoji: "(˘ω˘)", tint: .amber, cost: "$$"),
        DateCard(id: 113, title: "去 Cafe 各做各嘢",
                 detail: "你睇書我畫畫，唔出聲 2 個鐘",
                 mood: "靜", kaomoji: "(◍•ᴗ•◍)", tint: .sage, cost: "$"),
        DateCard(id: 114, title: "公園睇書一晝",
                 detail: "帶 1 本書 1 杯咖啡，攤喺草地",
                 mood: "靜", kaomoji: "(˘ω˘)", tint: .sage, cost: "$"),
        DateCard(id: 115, title: "屋企 candlelight dinner",
                 detail: "閂晒燈，點蠟燭，食簡單嘅意粉",
                 mood: "靜", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$"),
        DateCard(id: 116, title: "去廟拜一拜",
                 detail: "黃大仙或文武廟，求籤解籤",
                 mood: "靜", kaomoji: "(◕‿◕)", tint: .sage, cost: "$"),

        // ── 夢想 (dream) ──
        DateCard(id: 117, title: "去 IKEA 諗將來層樓",
                 detail: "唔買，淨係望，諗下將來想點佈置",
                 mood: "夢想", kaomoji: "(♡˙︶˙♡)", tint: .rose, cost: "$"),
        DateCard(id: 118, title: "睇 show flat",
                 detail: "假裝買樓，行 2 個示範單位",
                 mood: "夢想", kaomoji: "(◕‿◕)", tint: .rose, cost: "$"),
        DateCard(id: 119, title: "畫一齊住屋企嘅 floor plan",
                 detail: "Cafe 攤紙筆畫，每人輪流加一樣",
                 mood: "夢想", kaomoji: "(◍•ᴗ•◍)", tint: .amber, cost: "$"),
        DateCard(id: 120, title: "做一個 5 年 bucket list",
                 detail: "各寫 10 樣想一齊做嘅，逐樣 cross 出",
                 mood: "夢想", kaomoji: "(✧ω✧)", tint: .rose, cost: "$"),
    ]
}

enum QuizCatalog {
    static let all: [QuizQuestion] = [
        QuizQuestion(id: 1, question: "你最鍾意我邊度？",
                     kitAnswer: "你笑嗰陣眼仔彎彎",
                     michelAnswer: "你成日諗住其他人嘅心情"),
        QuizQuestion(id: 2, question: "我哋第一次去嘅餐廳叫乜？",
                     kitAnswer: "銅鑼灣嗰間意大利餐",
                     michelAnswer: "銅鑼灣嗰間意大利餐"),
        QuizQuestion(id: 3, question: "我最怕乜？",
                     kitAnswer: "蟑螂",
                     michelAnswer: "高度"),
    ]
}
