// Round-trip smoke tests for the crypto module.
//
// Run via `node --test lib/crypto/crypto.test.ts` from web/.
// These prove web-to-web works. iOS<->web wire compat requires a fixture
// generated by iOS (encrypt known payload with known keys + couple_id,
// paste base64 + expected plaintext here as a separate test vector).

import { test } from "node:test";
import assert from "node:assert/strict";

import { generateKeyPair, publicKeyFromBase64, publicKeyToBase64 } from "./keys";
import { deriveChatKey } from "./derive";
import { seal, open, sealBytes, openBytes } from "./seal";
import { textPayload, photoPayload } from "./payload";

test("X25519 keypair: public key is 32 bytes + base64 round-trips", () => {
  const kp = generateKeyPair();
  assert.equal(kp.privateKey.length, 32);
  assert.equal(kp.publicKey.length, 32);
  const b64 = publicKeyToBase64(kp.publicKey);
  const round = publicKeyFromBase64(b64);
  assert.deepEqual(Array.from(round), Array.from(kp.publicKey));
});

test("HKDF derives identical chatKey on both sides of pair", () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const coupleId = "11111111-2222-3333-4444-555555555555";
  const aliceKey = deriveChatKey(alice.privateKey, bob.publicKey, coupleId);
  const bobKey = deriveChatKey(bob.privateKey, alice.publicKey, coupleId);
  assert.deepEqual(Array.from(aliceKey), Array.from(bobKey));
  assert.equal(aliceKey.length, 32);
});

test("salt is case-insensitive (matches iOS uppercase default)", () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const lower = "abcdef12-3456-7890-abcd-ef1234567890";
  const upper = lower.toUpperCase();
  // Web client passing lower must derive same key as iOS passing upper.
  const fromLower = deriveChatKey(alice.privateKey, bob.publicKey, lower);
  const fromUpper = deriveChatKey(alice.privateKey, bob.publicKey, upper);
  assert.deepEqual(Array.from(fromLower), Array.from(fromUpper));
});

test("seal/open round-trips text payload", async () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const coupleId = "11111111-2222-3333-4444-555555555555";
  const chatKey = deriveChatKey(alice.privateKey, bob.publicKey, coupleId);

  const original = textPayload("hello 我哋 ❤");
  const cipher = await seal(original, chatKey);
  const decoded = await open(cipher, chatKey);
  assert.equal(decoded.kind, "text");
  assert.equal(decoded.text, "hello 我哋 ❤");
  assert.equal(decoded.v, 1);
});

test("seal/open round-trips photo payload", async () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const coupleId = "11111111-2222-3333-4444-555555555555";
  const chatKey = deriveChatKey(alice.privateKey, bob.publicKey, coupleId);

  const original = photoPayload("chat-media/abc-def.jpg");
  const cipher = await seal(original, chatKey);
  const decoded = await open(cipher, chatKey);
  assert.equal(decoded.kind, "photo");
  assert.equal(decoded.mediaHandle, "chat-media/abc-def.jpg");
});

test("alice can decrypt bob's message (cross-key seal)", async () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const coupleId = "11111111-2222-3333-4444-555555555555";

  const bobKey = deriveChatKey(bob.privateKey, alice.publicKey, coupleId);
  const aliceKey = deriveChatKey(alice.privateKey, bob.publicKey, coupleId);

  const bobMsg = textPayload("from bob");
  const cipher = await seal(bobMsg, bobKey);
  const decoded = await open(cipher, aliceKey);
  assert.equal(decoded.text, "from bob");
});

test("tampered ciphertext throws", async () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const coupleId = "11111111-2222-3333-4444-555555555555";
  const chatKey = deriveChatKey(alice.privateKey, bob.publicKey, coupleId);

  const original = textPayload("secret");
  const cipher = await seal(original, chatKey);
  // Flip a bit in the middle (past the nonce, inside ciphertext).
  const bytes = atob(cipher).split("").map(c => c.charCodeAt(0));
  bytes[20] ^= 0x01;
  const tamperedB64 = btoa(String.fromCharCode(...bytes));

  await assert.rejects(() => open(tamperedB64, chatKey));
});

test("sealBytes/openBytes round-trips arbitrary binary blob", async () => {
  const alice = generateKeyPair();
  const bob = generateKeyPair();
  const coupleId = "11111111-2222-3333-4444-555555555555";
  const chatKey = deriveChatKey(alice.privateKey, bob.publicKey, coupleId);

  // Simulate a 4 KiB PNG-like blob.
  const original = new Uint8Array(4096);
  crypto.getRandomValues(original);

  const sealed = await sealBytes(original, chatKey);
  // Must be exactly 12 (nonce) + plain.length + 16 (tag) bytes.
  assert.equal(sealed.length, 12 + original.length + 16);

  const round = await openBytes(sealed, chatKey);
  assert.equal(round.length, original.length);
  for (let i = 0; i < original.length; i++) {
    assert.equal(round[i], original[i]);
  }
});
